### ISSUE TITLE
Data reuse plan

### ISSUE THREAD

**Issue by ajspadial** [Akronix/birding#6]
Create a default Data reuse plan, or even a Data Management Plan, so that users know what happen with data they create or provide, and researchers and developers learn how to advantage of the datasets and quote them and the project properly.

@ajspadial may help wih that. In the end, he does this kind of this at his organization (@inia-es)

**Comment by Akronix** [comment]
hmm could you give us some more hints about this?
Maybe you could start first explaining us why we need this for our project and then you could propose something that you think that might match for birding?
We can also discuss about it in our [gitter room](https://gitter.im/Akronix/birding?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

**Comment by ajspadial** [comment]
OK. After talking with you last Friday it's clear **birding** should keep private most (of all) its data.

I have some considerations about the data workflow in the tool. I will write them down later and we can discuss them. 

Best.
